---
# tasks file for truedeploy-nodejs
- name: install epel repository && update system
  yum: name={{ item }} state=present update_cache=yes
  with_items:
    - epel-release
    - nodejs
    - npm
 
