---
# tasks file for truedeploy.sudouser

- name: creating sudo user
  user:
    name: "{{ user_name }}"
    groups: "{{ group_name }}"
    password: "{{ sudo_pass }}"
    state: present
#    system: yes
    update_password: on_create

